services:
  code-server:
    image: public.ecr.aws/f3w7h7x2/code-server:latest
    container_name: code-server
    env_file:
      - .env
    volumes:
      - ./config:/config
      - ./scripts:/opt/scripts
      - /home/aform/:/opt/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8443:8443
    networks:
      - common-network
    restart: unless-stopped
    shm_size: "1gb"
    group_add:
      - "20"          # dialout GID from the host — numeric, not the name
    labels:
      homelab.image.auto.update: true
      homelab.external.proxy.enabled: true
      homelab.external.proxy.domain: vsarr.htmlsketcher.com
      homelab.external.proxy.template: default
      homelab.external.proxy.internal.host: 192.168.100.5
      homelab.external.proxy.internal.port: 8443
      homelab.external.proxy.socket.path: /
    
networks:
  common-network:
    external: true