name: Build and Push code-server Image to AWS

on:
  workflow_dispatch:  # Manual trigger only

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY_ALIAS: f3w7h7x2
  IMAGE_NAME: code-server

# https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-amazon-elastic-container-service

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public

    - name: Build Docker Image
      run: docker build -t ${{ env.IMAGE_NAME }} .

    - name: Get next version
      uses: reecetech/version-increment@2023.10.2
      id: version
      with:
        scheme: semver
        increment: patch

    - name: Tag & Push Docker Image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker tag ${{ env.IMAGE_NAME }} $ECR_REGISTRY/${{ env.ECR_REGISTRY_ALIAS }}/${{ env.IMAGE_NAME }}:latest
        docker push $ECR_REGISTRY/${{ env.ECR_REGISTRY_ALIAS }}/${{ env.IMAGE_NAME }}:latest

    - name: Remove untagged images from ECR Public
      run: |
        IMAGE_IDS=$(aws ecr-public describe-images \
          --repository-name ${{ env.IMAGE_NAME }} \
          --region ${{ env.AWS_REGION }} \
          --query 'imageDetails[?imageTags==`null`].imageDigest' \
          --output text)

        if [ -z "$IMAGE_IDS" ]; then
          echo "No untagged images to remove."
        else
          for DIGEST in $IMAGE_IDS; do
            echo "Deleting untagged image $DIGEST"
            aws ecr-public batch-delete-image \
              --repository-name ${{ env.IMAGE_NAME }} \
              --region ${{ env.AWS_REGION }} \
              --image-ids imageDigest=$DIGEST
          done
        fi

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          Image is uploaded to [public repo](https://gallery.ecr.aws/f3w7h7x2/code-server) on AWS ECR.
        tag_name: ${{ steps.version.outputs.version }}
